language: java
install:
  - ./gradlew setupDecompworkspace
  - ./gradlew build
deploy:
  provider: releases
  api_key:
    secure: $OAUTH_TOKEN
  file_glob: true
  file: 
    - "build/libs/*.jar"
    - "README.md"
  skip_cleanup: true
  on:
    tags: false
