language: java
install:
  - ./gradlew setupDecompworkspace
  - ./gradlew build
before_deploy:
# Set up git user name and tag this commit
  - git config --local user.name "devdeploy"
  - git config --local user.email "devdeploy"
  - git tag "DevBuild-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: $OAUTH_TOKEN
  file_glob: true
  file: 
    - "build/libs/*.jar"
    - "README.md"
  skip_cleanup: true
  on:
    tags: false
    branches:
      - "master"
      - "dev"
      - "test"
