language: java
dist: trusty
install:
- jdk_switcher use oraclejdk8
- "./gradlew setupDecompworkspace"
- "./gradlew build"
before_deploy:
- git config --local user.name "testdeploy"
- git config --local user.email "testdeploy"
- git tag "$TRAVIS_BRANCH-build-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: b9ES+uRv/hTYwyIWhk0MPCBFBNRrgVH+ZJ5fNEfqdK2TrJP3cPAnkldNtr9WA8mFJBoXV1OR/0W0k9XL2NzelizqoBeMv2t8q6gHkBUGeENJuzbHQ9BfhCzmF4W5QLxuyF3O2wxbGengbN51G3qHv7exVpna1TVn3e+ostGDIYUVDbg1TyhdcQ2nCF2zeKuheosDWSOph3bsHWkzQghgbqKIs+C82NNK1+TGy2UfEW2ekY17EW0cFQk+6yv+ICVeZ6ZFjF/mjlOIAfO7vxYEeNGUSanQaXCtZqk+l+u8H+28ZAbOe+j/+Puo6nfwpozHsqN4KtCXVgs0Ph2eAElKQJ8KaGgUn9lw6dUeiMFNYaa+CqZv/9P8S7YWsaI2br0oI7xk3kI+NtjOGPxvXdFKqjQMtl46hU1vfGi5irTnhlbj/dMXLs7+2+Nha1py+9KI7Yszr1K8tafWH5t4T62hwooWPdnS/c5cXeJnvqKgkYTjvltjjHjeNCKr3rHtAZxo6dtGRs1cJmXHfyfx6fjFmWo9dOibpHQlJcDx9Pg0zZxRrkiiqpQrIa9AnknmsJY8Yiucp3cxRyrebw1taEy4a59sKrFi5JpFV76uDoSPrHfgA1ppmj7dY0oe6y1rDKkJXj0kWH/80qt2TdpOMoRHBl43NyMyGF9w5e0oER2g4xk=
  file:
  - build/libs/*.jar
  - README.md
  skip_cleanup: 'true'
  draft: true
  on:
    tags: false
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^dev|test|main$"
env:
  global:
  - secure: b9ES+uRv/hTYwyIWhk0MPCBFBNRrgVH+ZJ5fNEfqdK2TrJP3cPAnkldNtr9WA8mFJBoXV1OR/0W0k9XL2NzelizqoBeMv2t8q6gHkBUGeENJuzbHQ9BfhCzmF4W5QLxuyF3O2wxbGengbN51G3qHv7exVpna1TVn3e+ostGDIYUVDbg1TyhdcQ2nCF2zeKuheosDWSOph3bsHWkzQghgbqKIs+C82NNK1+TGy2UfEW2ekY17EW0cFQk+6yv+ICVeZ6ZFjF/mjlOIAfO7vxYEeNGUSanQaXCtZqk+l+u8H+28ZAbOe+j/+Puo6nfwpozHsqN4KtCXVgs0Ph2eAElKQJ8KaGgUn9lw6dUeiMFNYaa+CqZv/9P8S7YWsaI2br0oI7xk3kI+NtjOGPxvXdFKqjQMtl46hU1vfGi5irTnhlbj/dMXLs7+2+Nha1py+9KI7Yszr1K8tafWH5t4T62hwooWPdnS/c5cXeJnvqKgkYTjvltjjHjeNCKr3rHtAZxo6dtGRs1cJmXHfyfx6fjFmWo9dOibpHQlJcDx9Pg0zZxRrkiiqpQrIa9AnknmsJY8Yiucp3cxRyrebw1taEy4a59sKrFi5JpFV76uDoSPrHfgA1ppmj7dY0oe6y1rDKkJXj0kWH/80qt2TdpOMoRHBl43NyMyGF9w5e0oER2g4xk=
