language: java
install:
  - ./gradlew setupDecompworkspace
  - ./gradlew build
before_deploy:
# Set up git user name and tag this commit
  - git config --local user.name "testdeploy"
  - git config --local user.email "testdeploy"
  - git log -n 1 --pretty=%d HEAD
  - echo $GIT_BRANCH | cut -d / -f 2
  - git tag "$(git log -n 1 --pretty=%d HEAD| cut -d ' ' -f4 | cut -d ',' -f1)Build-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: $OAUTH_TOKEN
  file_glob: true
  file: 
    - "build/libs/*.jar"
    - "README.md"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^dev|test|master$
