language: java
dist: trusty
install:
- jdk_switcher use oraclejdk8
- "./gradlew setupDecompworkspace"
- "./gradlew build"
before_deploy:
- git config --local user.name "testdeploy"
- git config --local user.email "testdeploy"
- git tag "$TRAVIS_BRANCH-build-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: IbMGSfFeJDX2998WS30Jg74+okCgP8ZmHb4N/x9r7/yNdm35LppqsyzTuT9QJCY5WIpCdJUcQFrRnuHaXfr+KmZ4hH0HIS5JombNx/QoKoteiU8C35ZPYu9li4jbBRW42XejXDQPwHLaKziMAZ3vDRIxK2YYIc8+3y0u7zg2ZDcvnn2CDYkD9TjlkbDem9yghmbbCPjTQ8Ukqr2F6KgtzjS0dvnscyVuO8XBuDKO/ETRdVOSKJRcp8+ZpqpnndCU2+HaBAOqS+wb4IXkdkQDUlU1BG+a+SJXdUdbPEiHSVyOIrT/ktBSEgqEfwlfUO4I2w0QvV5QkGodT1fLuV8Qx54618X7/BrbiELXAzHm79K2IyyHX0VSoM9GwAMg9uz7K3iN4bWCyK1xXXY+RhOCPg0ChltN6jxDgK1Wifi/NfLHdPZ7gIOA9KO/0bNeBwk9fJLpvXo3v/Kt6c6tZSEjtYVzAU2bVB2KCkFgEtvbXVkeJT5sCIlEXHSuDiakH0CGhDkQ/jiEvynBsUAH0FoHW6bBPDasyarw9PEtgbwRcm/yOazv46Prf3JuMZqfsVf5RKR3wgal20FwPS0FbMzWuCANcx6Lx6zUevZlpIvoHujYO1xsrlNSU83tVnZh0gLnO4eqsVy4n0l1eCuJ+88xrXYx/f3SteCm6E++FOGRuFk=
  file:
  - build/libs/*.jar
  - README.md
  on:
    tags: false
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^dev|test|main$"
    repo: BearsDen989-GT/Gregtech-5u-Bears-Den-Edition
    branch: main
  skip_cleanup: 'true'
  draft: 'true'
#env:
#  global:
#  - secure: phDf8PGUg1ikNRaN6Qv/lQme6oFjWeqfc6WRelyUdGTzhtc0uCmbDZypL+EY9iGJfp5GA7eWbUfeUwuojcUCfBRQ0KJmOGkJDIcTsJ2lMUtZzXVTUQOMPMVb6nLPFfkk2oQL8dZpYiLKiuD4dGQnuzx/M3MG7auOPLhEc34uFKewc5MiLhXJaWR2YAlIhGPjEIiM0Ct6WSKHqMTA6F0gWEq4IwgsbV7CbEFAShEzxyt+3qWs/HjwApCvR9ycT2JOTyUvaojoBHAURO67zc3iNr5MBnIczKWoAc2jcWS8tsXKN7ebddVdvBsgDlBYkHOdijPFfMzKRmTRGd1n5MncFvx21zqSeNhip/lWOZUbToEJNc/zr2Wh/1j3pMVtdfxEeVNCe8SnSXjReuYJnm0tx95XTj5f7sfG1gpu+XwUUPDJB//0e+7kIpjYExp9WAwclRIgHdY82pEhUbLwjEm8/GHa79Oe2eFghVidvnKghXyUN75BSCjON8BCfNERg0jxHoUi7D5944hcedPt5oFmexLprLpT70yI3Tqupo7TR6YyN+KuWBPmjLG0t3aJ/9R20kHt73z/XoMhrS5maI9+JFbv5tmTlOlj8wvVjAJ1wkGOrA2VKVIY8MTFPMIt+DUhqYHe6f4wxQNHoc1dq3d4Yj/m3QHqSxRKTQS7CuGV+wU=
