language: java
dist: trusty
install:
- jdk_switcher use oraclejdk8
- "./gradlew setupDecompworkspace"
- "./gradlew build"
before_deploy:
- git config --local user.name "testdeploy"
- git config --local user.email "testdeploy"
- git tag "$TRAVIS_BRANCH-build-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: qI0slpwH4CcAXhMopKhtLRi8JrSGwp8hYIwofoOYZ1x0ZHzAlX00dU/JiCKsDyW11FFQnAn0yhH+wpEnCRA3GROAEUjn1BkongDYeCHcQ3DTWmvuaYDPg0gJioT82d5OX6/SfdtmvSjXKp7TMmE8zvr2GM2aLqukE3PHzYT1LI/LPmDfWg4OFOd+6LlQ2S1ff+bP1mskQvRf4uazMdA73RsRFFis2S5s7qM5JBwkxMioxq9gBDSxbX9pR/0xIxFye069EksHJEJlhbzsJJLuvG9NKstx9LV8rKwtHRHo1YhkKw4RTUxNp+wypolMVND3s8GArez95PYdTzP+bMa2fC8d16nKrO1ZRfQmWFInkbsJS9yMPN9uufpwYmGzODFtI2vc4CihfxH/Qk4noiqlhj9bBl3K3IkTQOn1k5s7bXM9IXeqVRAt2t+F4jBDuaxbKWGBU0jZVB+ais/ahuxJ4mUyEh/EY+L1gG0bROygLBC5vkhbgtHF0FJvHw6rZ65Sp1L1Oo/hTMkpZL/bIBDpB98TNaIKPB8+4ZF1862ZvKmFQgooAy2r/gQpTBQ5SATzPcN7QPWN+1bhEHuhuzHuV/hc1R8xr1J5PmBaYmAXomqckmslrBDFzKPMLcxyQM+xx/hKk9xpyfGbveQzUGEw1ELPzxUgEBc3VeQdBbnHgU4=
  file:
  - build/libs/*.jar
  - README.md
  skip_cleanup: 'true'
  draft: true
  on:
    tags: false
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^dev|test|main$"
env:
  global:
  - secure: qI0slpwH4CcAXhMopKhtLRi8JrSGwp8hYIwofoOYZ1x0ZHzAlX00dU/JiCKsDyW11FFQnAn0yhH+wpEnCRA3GROAEUjn1BkongDYeCHcQ3DTWmvuaYDPg0gJioT82d5OX6/SfdtmvSjXKp7TMmE8zvr2GM2aLqukE3PHzYT1LI/LPmDfWg4OFOd+6LlQ2S1ff+bP1mskQvRf4uazMdA73RsRFFis2S5s7qM5JBwkxMioxq9gBDSxbX9pR/0xIxFye069EksHJEJlhbzsJJLuvG9NKstx9LV8rKwtHRHo1YhkKw4RTUxNp+wypolMVND3s8GArez95PYdTzP+bMa2fC8d16nKrO1ZRfQmWFInkbsJS9yMPN9uufpwYmGzODFtI2vc4CihfxH/Qk4noiqlhj9bBl3K3IkTQOn1k5s7bXM9IXeqVRAt2t+F4jBDuaxbKWGBU0jZVB+ais/ahuxJ4mUyEh/EY+L1gG0bROygLBC5vkhbgtHF0FJvHw6rZ65Sp1L1Oo/hTMkpZL/bIBDpB98TNaIKPB8+4ZF1862ZvKmFQgooAy2r/gQpTBQ5SATzPcN7QPWN+1bhEHuhuzHuV/hc1R8xr1J5PmBaYmAXomqckmslrBDFzKPMLcxyQM+xx/hKk9xpyfGbveQzUGEw1ELPzxUgEBc3VeQdBbnHgU4=
